# Generated by Django 2.1.3 on 2018-11-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
