# Generated by Django 2.1.3 on 2018-11-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20181127_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
