# Generated by Django 2.1.3 on 2018-11-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='front_user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
